default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: ""
  database: word_application_dev
  host: db

test:
  <<: *default
  username: postgres
  password: ""
  database: word_application_test
  host: db

production:
  <<: *default
  database: word_application
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>

